### ISSUE TITLE
Things that maybe should be implemented

### ISSUE THREAD

**Issue by balinskia** [Getline-Network/ethereum-contracts#3]
In [InvestorLedger](https://github.com/Getline-Network/ethereum-contracts/blob/master/contracts/loans/InvestorLedger.sol) :

1. We don't add investors to the investor ledge.investors. But for example we delete them in function withdrawInvestment(...)

**2. We don't send money from investors to investorLedger in: gatherInvestment(...)**

3. In: gatherInvestment(...): total Payback needed is badly implemented. It only sums the interests, not the amount we lended

**Comment by q3k** [comment]
Consider breaking down this issue into multiple sub-issues.

**Comment by balinskia** [comment]
Issue broke down, see issues: #4 and #6
